ci: disable the delivery of the zip files

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -98,37 +98,37 @@ jobs:
           artifacts: ${{ steps.compile.outputs.compiled-files }}
           replacesArtifacts: true
           tag: ${{ needs.compute-version.outputs.version }}
-  deploy-archives:
-    runs-on: ubuntu-latest
-    needs:
-      - compute-version
-    steps:
-      - name: Verify the version
-        run: ruby -e 'unless /^\d+\.[1-9]\d*\.[1-9]\d*$/.match?("${{ needs.compute-version.outputs.version }}") then exit 1 end'
-      - name: Checkout
-        uses: danysk/action-checkout@0.2.2
-      - name: Remove PMD/Checkstyle/Spotbugs configuration from the first labs
-        run: ./cleanup_project_files.rb
-      - name: Create archives
-        id: archive
-        run: |
-          for file in workspace/*/; do
-            name="${file#*/}"
-            destination="${name%*/}.zip"
-            echo Creating "$destination" from $file
-            zip -r "$destination" "$file"
-            results="$results,$destination"
-          done
-      - name: Release
-        if: >-
-          (github.event_name == 'push' && github.ref == 'refs/heads/master')
-          || github.event_name == 'workflow_dispatch'
-          || github.event_name == 'workflow_run'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        uses: ncipollo/release-action@v1.10.0
-        with:
-          allowUpdates: true
-          artifacts: "*.zip"
-          replacesArtifacts: true
-          tag: ${{ needs.compute-version.outputs.version }}
+  # deploy-archives:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - compute-version
+  #   steps:
+  #     - name: Verify the version
+  #       run: ruby -e 'unless /^\d+\.[1-9]\d*\.[1-9]\d*$/.match?("${{ needs.compute-version.outputs.version }}") then exit 1 end'
+  #     - name: Checkout
+  #       uses: danysk/action-checkout@0.2.2
+  #     - name: Remove PMD/Checkstyle/Spotbugs configuration from the first labs
+  #       run: ./cleanup_project_files.rb
+  #     - name: Create archives
+  #       id: archive
+  #       run: |
+  #         for file in workspace/*/; do
+  #           name="${file#*/}"
+  #           destination="${name%*/}.zip"
+  #           echo Creating "$destination" from $file
+  #           zip -r "$destination" "$file"
+  #           results="$results,$destination"
+  #         done
+  #     - name: Release
+  #       if: >-
+  #         (github.event_name == 'push' && github.ref == 'refs/heads/master')
+  #         || github.event_name == 'workflow_dispatch'
+  #         || github.event_name == 'workflow_run'
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       uses: ncipollo/release-action@v1.10.0
+  #       with:
+  #         allowUpdates: true
+  #         artifacts: "*.zip"
+  #         replacesArtifacts: true
+  #         tag: ${{ needs.compute-version.outputs.version }}
